version: '3.8'

services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: voj-dynamodb-local
    ports:
      - "8001:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    environment:
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_DEFAULT_REGION=ap-northeast-2
    networks:
      - voj-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # DynamoDB Admin (웹 UI로 DynamoDB Local 관리)
  dynamodb-admin:
    image: "aaronshaf/dynamodb-admin:latest"
    container_name: voj-dynamodb-admin
    ports:
      - "8002:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=ap-northeast-2
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    depends_on:
      dynamodb-local:
        condition: service_healthy
    networks:
      - voj-network
    restart: unless-stopped

networks:
  voj-network:
    driver: bridge
    name: voj-network

volumes:
  dynamodb-data:
    driver: local
